config/routes.rb
CmuSds::Application.routes.draw do
  devise_for :users
  root :to => 'home#index'

  match 'dashboard' => 'home#dashboard', :as => "dashboard"

  resources :sensor_readings, :devices, :device_agents, :sensor_types, :device_types, :locations
  resources :sensors

  match '/get_devices' => 'devices#get_devices'
  match ':controller(/:action(/:id))(.:format)'
end

app/models/device.rb
class Device < ActiveRecord::Base
    attr_accessible :guid, :uri, :device_type_id, :network_address, :metadata_json, :print_name, :config, :url

    #has_many :device_registries
    has_and_belongs_to_many :device_agents
    belongs_to :device_type
    has_one :location, :dependent => :destroy
    has_many :sensors, :dependent => :destroy

    def as_json(options={})
      {
        :uri => self.uri,
        :sensors => self.sensors
      }
    end

    before_create do
        self.guid = SecureRandom.uuid
    end

end

app/models/device_type.rb
class DeviceType < ActiveRecord::Base
    attr_accessible :device_type, :version, :manufacturer, :metadata_json, :default_config
    has_many :devices
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  respond_to :json, :html

  def index
    @devices = Device.all
    respond_with @devices
  end

  def get_devices
    @devices = Device.all
    device_hash = @devices.collect { |d|
      loc = {}
      if d.location.nil?
        loc = {:lat => '', :lon => '', :alt => ''}
      else
        loc[:lat] = d.location.lat.nil? ? nil : d.location.lat
        loc[:lon] = d.location.lon.nil? ? nil : d.location.lon
        loc[:alt] = d.location.alt.nil? ? nil : d.location.alt
        loc[:format] = d.location.format.nil? ? nil : d.location.format
      end
      Hash[
          :guid => d.guid,
          :uri => d.uri,
          :print_name => d.print_name,
          :location => loc,
          :sensors => d.sensors.collect{|s| Hash[s.guid => s.sensor_type.property_type]}
      ]
    }
    render :json => device_hash
  end

  def new
    @location = Location.new
    @device_types = DeviceType.all
    @device_agents = DeviceAgent.all
    if (!params[:uri].blank? && !params[:device_type_id].blank?)   # && !params[:physical_location].nil? && !params[:network_address].nil?)
      @device = Device.new(:uri => params[:uri], :device_type_id => params[:device_type_id])
      @device.network_address = params[:network_address] unless params[:network_address].blank?
      @device.save
                                                                   #redirect_to devices_path
    else
      @device = Device.new
      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @device }
      end
    end
  end

  def create
    @device = Device.new(params[:device])
    if @device.save

      @location = Location.create({
                                      :lat => params[:lat],
                                      :lon => params[:lon],
                                      :alt => params[:alt],
                                      :format => params[:pos_fmt]
                                  })
      @device.location = @location

      # pre-populate sensors for firefly device
      # if @device.device_type_id == "1"   # firefly_v2 has an id of 1
      if !(@device.device_type.default_config.blank?)

        # get the sensor types to add by default for a device of this config
        default_config_json = JSON.parse(@device.device_type.default_config)

        # initialize the uri for this device (only for sensor creation)
        temp_device_uri  = @device.uri.sub(/#{@device.id}\./, '')
        temp_device_uri = temp_device_uri.sub(/\.device\.sv\.cmu\.edu/, '')
        # @device.uri = @device.id.to_s << "." << @device.uri << ".device.sv.cmu.edu"


        # replace with property_type
        default_config_json["property_type"].each do |pt|
          # find Sensor type with property pt
          st = SensorType.find_by_property_type(pt)
          # create Sensor with this Sensor Type
          [{
               :uri => ".sensor.sv.cmu.edu",
               :sensor_type_id => st.id,
               :uri => @device.uri,
               :device_id => @device.id
           }].each do |attributes|
            s = Sensor.create(attributes)
            s.uri = s.id.to_s << "." << temp_device_uri << s.uri
            s.save
            # add this Sensor to the Sensor Type
            st.sensors << s
            # add Sensor to the device
            @device.sensors << s
          end
        end
        @device.save
      end

      flash[:notice] = "Device created successfully !"
      redirect_to :action => "index"
    else
      format.html { render action: "new" }
      render "new"
      format.js
    end

  end

  def edit
    @device = Device.find(params[:id])
    # @device.uri = @device.uri.sub(/#{@device.id}\./, '')
    # @device.uri = @device.uri.sub(/\.device\.sv\.cmu\.edu/, '')
    @location = @device.location.nil? ? Location.new : @device.location
    @device_types = DeviceType.all
    @device_agents = DeviceAgent.all
    @sensors = @device.sensors
  end

  def update
    @device = Device.find(params[:id])

    device_agent = DeviceAgent.find_by_id(params[:device_agent_id])
    @device.device_agents << device_agent unless @device.device_agents.include? device_agent

    respond_to do |format|
      if @device.update_attributes(params[:device])
        @location = Location.create({
                                        :lat => params[:lat],
                                        :lon => params[:lon],
                                        :alt => params[:alt],
                                        :format => params[:pos_fmt]
                                    })
        @device.location = @location
        # @device.device_agents << params[:device_agent]
        # @device.uri = @device.id.to_s << "." << @device.uri << ".device.sv.cmu.edu"
        @device.save
        ask_device_to_update(@device)
        flash[:notice] = 'Device  was successfully updated.'
        format.html { redirect_to :action => "index" }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @device = Device.find(params[:id])
    @device.delete
    flash[:notice] = "Device deleted successfully !"
    redirect_to :action => "index"
  end

  def show
    redirect_to :action => "edit"
  end

  def get
    d = Device.find(params[:id])

    loc = {}
    if d.location.nil?
      loc = {:lat => '', :lon => '', :alt => ''}
    else
      loc[:lat] = d.location.lat.nil? ? nil : d.location.lat
      loc[:lon] = d.location.lon.nil? ? nil : d.location.lon
      loc[:alt] = d.location.alt.nil? ? nil : d.location.alt
      loc[:format] = d.location.format.nil? ? nil : d.location.format
    end
    device_hash =
        Hash[
        :guid => d.guid,
        :uri => d.uri,
        :print_name => d.print_name,
        :location => loc,
        :sensors => d.sensors.collect{|s| Hash[s.guid => s.sensor_type.property_type]}
    ]
    render :json => device_hash
  end

  def get_config_by_uri
    d = Device.find_by_uri(params[:id])
    device_hash = get_device_config_json(d)
    render :json => device_hash
  end

  def ask_device_to_update( device )
    begin
      @result = HTTParty.post(device.url.to_str,
                              :body => get_device_config_json(device).to_json,
                              :headers => { 'Content-Type' => 'application/json' } )
    rescue Exception=>e
      # handle e
    end

    puts "got"
  end

  def get_device_config_json(d)
    device_hash =
        Hash[
            :guid => d.guid,
            :uri => d.uri,
            :print_name => d.print_name,
            :config => d.config,
            :sensors => d.sensors.collect{|s| Hash[s.guid => s.frequency]}
        ]

    return device_hash
  end
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/devices/_form.html.erb
<%= form_for(@device) do |f| %>
    <% if @device.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@device.errors.count, "error") %> prohibited this device from being registered:</h2>

          <ul>
            <% @device.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <table>
      <tr>
        <td class="field" width="50%"><label for="guid" />GUID</td>
        <td class="field"><%= f.text_field :guid,:readonly => true %> <span>auto-generated</span></td>
      </tr>
      <tr>
        <td class="field"><label for="device_uri" />URI</td>
        <td class="field"><%= f.text_field :uri %></td>
      </tr>
      <tr>
        <td class="field"><%= f.label :device_type_id %></td>
        <td class="field"><%= f.select("device_type_id", options = @device_types.map { |d| [d.device_type, d.id] }) %></td>
      </tr>
      <tr>
        <td class="field"><%= f.label :device_agent_id %></td>
        <td class="field">
          <select name="device_agent_id">
            <% @device_agents.each do |da|%>
                <option value="<%=da.id%>"><%=da.print_name%></option>
            <% end %>
          </select>
        </td>
      </tr>
      <tr>
        <td class="field"><%= f.label :network_address %></td>
        <td class="field"><%= f.text_field :network_address %></td>
      </tr>
      <tr>
        <td class="field"><%= f.label :latitude %></td>
        <td class="field"><input type='text' name='lat' value="<%= @location.lat %>" /></td>
      </tr>
      <tr>
        <td class="field"><%= f.label :longitude %></td>
        <td class="field"><input type='text' name='lon' value="<%= @location.lon %>" /></td>
      </tr>
      <tr>
        <td class="field"><%= f.label :altitude %></td>
        <td class="field"><input type='text' name='alt' value="<%= @location.alt %>" /></td>
      </tr>
      <tr>
        <td class="field"><%= f.label :position_format_type %></td>
        <td class="field">
          <select name='pos_fmt'>
            <option value='wgs84' <%= h 'selected' if @location.format == 'wgs84' %>>GPS - WGS84</option>
            <option value='xyz' <%= h 'selected' if @location.format == 'xyz' %>>XYZ Coordinates</option>
          </select>
        </td>
      </tr>
        <td class="field"><label for="device_url" />Device URL</td>
        <td class="field"><%= f.text_field :url %></td>
      </tr>
      <tr>
        <td class="field" width="50%"><%= f.label :config %></td>
        <td class="field"><%= f.text_area   :config, :rows => '10',
                                            :placeholder => "{\"frequency\": \"1\",\"post_url\": \"http://api.sen.se/events/?sense_key=RMSHIf10oCKD22_NINkGsg\", \"temp_feed_id\": \"38549\" ,
                              \"pressure_feed_id\": \"38550\" , \"motion_feed_id\": \"38551\" , \"humidity_feed_id\": \"38552\" , \"x_acceleration_feed_id\": \"38553\",
                              \"y_acceleration_feed_id\": \"38554\" , \"z_acceleration_feed_id\": \"38555\" , \"light_feed_id\": \"38556\" , \"microphone_feed_id\": \"38557\"}"
        %></td>
        <!--
           sample json for Firefly config
            {"property_type": [
           "Temperature",
           "Digital Temperature",
           "Light",
           "Pressure",
           "Humidity",
           "Motion",
           "Audio P2P",
           "Accelerometer x",
           "Accelerometer y",
           "Accelerometer z"]}
        -->
      </tr>
      <tr>
        <td style="text-align: right;" colspan="2">
            <div class="actions">
              <%= f.submit %>
            </div>
        </td>
      </tr>
    </table>
<% end %>

<section class="intro clearfix">
    <div class="limiter">
        <div class="item">
          <a href="#">
            <h3>TODOs:</h3>
            <p>
                <ul>
                    <li>Network address e.g. 231000003</li>
                    <li>When providing GPS coordinates, provide a way to enter free form text in the various popular formats. Parse it in the backend to appropriate coordinates.e.g. Deg, Min, Second or just Deg etc.</li>
                    <li>The conversion mentioned above is from the manufacturer's documentation. If a general conversion is preferred like deg C to deg F, create a virtual sensor as a wrapper to this.</li>
                    <li>Add a check to see if uri is unique (from database)</li>
                </ul>
            </p>
          </a>
        </div>
    </div>
</section>

app/views/devices/edit.html.erb
<div class="container">
<% @page_title = "| Devices | Edit" %>

<h1 style="text-align: left;">Edit Device Information</h1>
<%= render 'form' %>
	<h2>Device Agents for this Device:</h2>
		<table class="field" width="50%">
		<thead>
			<tr>
				<td><u>Location</u></td>
				<td><u>URI</u></td>
		<% @device_agents.each do |da| %>
			<tr>
				<td><%= link_to da.print_name, edit_device_agent_path(da) %></td>
				<td><%= link_to da.uri, edit_device_agent_path(da) %></td>
			</tr>
		<% end %>
	</table><br />
	<h2>Sensors for this device:</h2>
		<table class="field" width="50%">
		<thead>
			<tr>
				<td><u>Child Sensors</u></td>
				<td><u>Sensor Type</u></td>
		<% @sensors.each do |sensor| %>
			<tr>
				<td><%= link_to sensor.guid, edit_sensor_path(sensor) %></td>
				<td><%= sensor.sensor_type.property_type %></td>
			</tr>
		<% end %>
	</table><br />
<%= link_to 'Back', devices_path %>
</div>

app/views/devices/index.html.erb
<div class="container">
<% @page_title = "| Device | List" %>

<h1 style="text-align: left;">List of Devices</h1>

    <table class="table">
        <tr>
            <td>Device URI</td>
            <td>Device Type</td>
            <td>network_address</td>
            <td>physical_location</td>
            <td colspan='2'>Actions</td>
        </tr>
        <% @devices.each do |device| %>
        <tr>
            <td><%= link_to device.uri, edit_device_path(device) %></td>
            <td><%= device.device_type.device_type %></td>
            <td><%= device.network_address %></td>
            <td><% unless device.location.blank? %>
                <%= "lat: #{device.location.lat}" unless device.location.lat.nil? %><%= ", lon: #{device.location.lon}" unless device.location.lon.nil? %><%= ", alt: #{device.location.alt}" unless device.location.alt.nil? %>
            <% end %></td>
            <td><%= link_to 'Edit', edit_device_path(device) %></td>
            <td><%= link_to 'Delete', device, confirm: 'Are you sure?', method: :delete %></td>
        </tr>
        <% end %>
    </table>
<%= link_to 'New', new_device_path %> | <%= link_to 'Back', dashboard_path %>
</div>

app/views/devices/new.html.erb
<div class="container">
<% @page_title = "| Device | New" %>

<h1 style="text-align: left;">Device registration</h1>
<%= render 'form' %>
<%= link_to 'Back', devices_path %>
</div>