config/routes.rb
CmuSds::Application.routes.draw do
  devise_for :users
  root :to => 'home#index'

  match 'dashboard' => 'home#dashboard', :as => "dashboard"

  resources :sensor_readings, :devices, :device_agents, :sensor_types, :device_types, :locations
  resources :sensors

  match '/get_devices' => 'devices#get_devices'
  match ':controller(/:action(/:id))(.:format)'
end

app/models/conversion.rb
class Conversion < ActiveRecord::Base
  attr_accessible :device_type_id, :quantity, :description, :conversion_type, :a, :b, :chart_min, :chart_max

  belongs_to :device_type

end

app/models/device.rb
class Device < ActiveRecord::Base
    attr_accessible :guid, :uri, :device_type_id, :network_address, :metadata_json, :print_name, :config, :url

    #has_many :device_registries
    has_and_belongs_to_many :device_agents
    belongs_to :device_type
    has_one :location, :dependent => :destroy
    has_many :sensors, :dependent => :destroy

    def as_json(options={})
      {
        :uri => self.uri,
        :sensors => self.sensors
      }
    end

    before_create do
        self.guid = SecureRandom.uuid
    end

end

app/models/device_agent.rb
class DeviceAgent < ActiveRecord::Base
	attr_accessible :guid, :uri, :network_address, :print_name, :metadata_json
	has_and_belongs_to_many :devices
	has_one :location, :dependent => :destroy

  	before_create do
	    self.guid = SecureRandom.uuid
	end
end

app/models/device_registry.rb
class DeviceRegistry < ActiveRecord::Base
    belongs_to :device
    belongs_to :device_agent
  # attr_accessible :title, :body
end

app/models/device_type.rb
class DeviceType < ActiveRecord::Base
    attr_accessible :device_type, :version, :manufacturer, :metadata_json, :default_config
    has_many :devices
end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :alt, :format, :lat, :lon, :print_name
end

app/models/locations.rb
class Locations < ActiveRecord::Base
	attr_accessible :alt, :format, :lat, :lon, :print_name
	belongs_to :device
	belongs_to :sensor
	belongs_to :device_agent
end

app/models/sensor.rb
class Sensor < ActiveRecord::Base
  attr_accessible :guid, :uri, :sensor_type_id, :min_value, :max_value, :device_guid, :device_id, :predecessor, :metadata_json, :location, :frequency
  belongs_to :device
  belongs_to :sensor_type
  has_one :location, :dependent => :destroy

	before_create do
	    self.guid = SecureRandom.uuid
	end
end

app/models/sensor_reading.rb
class SensorReading < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/sensor_registry.rb
class SensorRegistry < ActiveRecord::Base
    has_many :sensors
  # attr_accessible :title, :body
end

app/models/sensor_type.rb
class SensorType < ActiveRecord::Base
    attr_accessible :property_type, :metadata_json
    has_many :sensors
end

app/models/sensor_type_registry.rb
class SensorTypeRegistry < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/virtual_device.rb
class VirtualDevice < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/virtual_sensor.rb
class VirtualSensor < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index

  end

  def dashboard

  end

end

app/controllers/sensors_controller.rb
class SensorsController < ApplicationController
    respond_to :json, :html

    def index
        @sensors = Sensor.all
        respond_with @sensors
    end

    def new
        @sensor_types = SensorType.all
        @devices = Device.all
        @location = Location.new
        if (!params[:guid].blank? && !params[:device_id].blank?)
            @sensor = Sensor.new(:guid => params[:guid], :device_id => params[:device_id])
            @sensor.sensor_type_id = params[:sensor_type_id] unless params[:sensor_type_id].blank?
            @sensor.min_value = params[:min_value] unless params[:min_value].blank?
            @sensor.max_value = params[:max_value] unless params[:max_value].blank?
            @sensor.device_guid = params[:device_guid] unless params[:device_guid].blank?
            @sensor.predecessor = params[:predecessor] unless params[:predecessor].blank?
            @sensor.metadata_json = params[:metadata_json] unless params[:metadata_json].blank?
            @sensor.gps_coord_lat = params[:gps_coord_lat] unless params[:gps_coord_lat].blank?
            @sensor.gps_coord_long = params[:gps_coord_long] unless params[:gps_coord_long].blank?
            @sensor.gps_coord_alt = params[:gps_coord_alt] unless params[:gps_coord_alt].blank?
            @sensor.save
        else
            @sensor = Sensor.new
        end
    end

    def create
        @sensor = Sensor.new(params[:sensor])
        if @sensor.save
            flash[:notice] = "Sensor created successfully !"
            redirect_to :action => "index"
        else
            flash[:error] = "Couldn't create the Sensor. Please try again."
            render "new"
        end
    end
    def edit
        @sensor = Sensor.find(params[:id])
        @location = @sensor.location
        @sensor_types = SensorType.all
        @devices = Device.all
    end

    def update
        @sensor = Sensor.find(params[:id])
        respond_to do |format|
            if @sensor.update_attributes(params[:sensor])
                flash[:notice] = 'Sensor  was successfully updated.'
                format.html { redirect_to :action => "index" }
                format.json { head :no_content }
            else
              format.html { render action: "edit" }
              format.json { render json: @sensor.errors, status: :unprocessable_entity }
            end
        end
    end

    def destroy
        @sensor = Sensor.find(params[:id])
        @sensor.delete
        flash[:notice] = "Sensor deleted successfully !"
        redirect_to :action => "index"
    end

    def show
        redirect_to :action => 'edit'
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/device_types_helper.rb
module DeviceTypesHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/sensor_types_helper.rb
module SensorTypesHelper
end

app/helpers/sensors_helper.rb
module SensorsHelper
end

app/views/sensors/_form.html.erb
<%= form_for(@sensor) do |f| %>
    <% if @sensor.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@sensor.errors.count, "error") %> prohibited this sensor from being registered:</h2>

          <ul>
            <% @sensor.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <table>
      <tr>
        <td class="field" width="50%"><label for="guid" />GUID</td>
        <td class="field"><%= f.text_field :guid,:readonly => true %> <span>auto-generated</span></td>
      </tr>
      <tr>
        <td class="field"><%= f.label :sensor_type_id %></td>
        <td class="field"><%= f.select("sensor_type_id", options = @sensor_types.map { |s| [s.property_type, s.id] }) %></td>
      </tr>
      <tr>
        <td class="field"><%= f.label :min_value %></td>
        <td class="field"><%= f.text_field :min_value %></td>
      </tr>
      <tr>
        <td class="field"><%= f.label :max_value %></td>
        <td class="field"><%= f.text_field :max_value %></td>
      </tr>
      <tr>
        <td class="field"><%= f.label :device_guid %></td>
        <td class="field"><%= f.select("device_guid", options = @devices.map { |d| [d.uri, d.id] }) %></td>
      </tr>
      <tr>
        <td class="field"><%= f.label :predecessor %></td>
        <td class="field"><%= f.text_field :predecessor %></td>
      </tr>
      <tr>
        <td class="field"><%= f.label :metadata_json %></td>
        <td class="field"><%= f.text_field :metadata_json %></td>
      </tr>



      <tr>
        <td style="text-align: right;" colspan="2">
            <div class="actions">
              <%= f.submit %>
            </div>
        </td>
      </tr>
    </table>
<% end %>

app/views/sensors/edit.html.erb
<div class="container">
<% @page_title = "| Sensors | Edit" %>

<h1 style="text-align: left;">Edit Sensor Information</h1>
<%= render 'form' %>
<%= link_to 'Back', sensors_path %>
</div>

app/views/sensors/index.html.erb
<div class="container">
<% @page_title = "| Sensors | List" %>

<h1 style="text-align: left;">List of Sensors</h1>

    <table class="table">
        <tr>
            <td>guid</td>
            <td>Sensor Type</td>
            <td>Parent Device</td>
            <td colspan='2'>Actions</td>
        </tr>
        <% @sensors.each do |sensor| %>
        <tr>
            <td><%= sensor.guid %></td>
            <td><%= sensor.sensor_type_id %></td>
            <td><%= link_to sensor.device.uri, device_path(sensor.device) %></td>
            <td><%= link_to 'Edit', edit_sensor_path(sensor) %></td>
            <td><%= link_to 'Delete', sensor, confirm: 'Are you sure?', method: :delete %></td>
        </tr>
        <% end %>
    </table>

<%= link_to 'New', new_sensor_path %> | <%= link_to 'Back', dashboard_path %>
</div>

app/views/sensors/new.html.erb
<div class="container">
<% @page_title = "| Sensors | New" %>

<h1 style="text-align: left;">New Sensor Information</h1>
<%= render 'form' %>
<%= link_to 'Back', sensors_path %>
</div>