config/routes.rb
CmuSds::Application.routes.draw do
  devise_for :users
  root :to => 'home#index'

  match 'dashboard' => 'home#dashboard', :as => "dashboard"

  resources :sensor_readings, :devices, :device_agents, :sensor_types, :device_types, :locations
  resources :sensors

  match '/get_devices' => 'devices#get_devices'
  match ':controller(/:action(/:id))(.:format)'
end

app/models/conversion.rb
class Conversion < ActiveRecord::Base
  attr_accessible :device_type_id, :quantity, :description, :conversion_type, :a, :b, :chart_min, :chart_max

  belongs_to :device_type

end

app/models/device.rb
class Device < ActiveRecord::Base
    attr_accessible :guid, :uri, :device_type_id, :network_address, :metadata_json, :print_name, :config, :url

    #has_many :device_registries
    has_and_belongs_to_many :device_agents
    belongs_to :device_type
    has_one :location, :dependent => :destroy
    has_many :sensors, :dependent => :destroy

    def as_json(options={})
      {
        :uri => self.uri,
        :sensors => self.sensors
      }
    end

    before_create do
        self.guid = SecureRandom.uuid
    end

end

app/models/device_agent.rb
class DeviceAgent < ActiveRecord::Base
	attr_accessible :guid, :uri, :network_address, :print_name, :metadata_json
	has_and_belongs_to_many :devices
	has_one :location, :dependent => :destroy

  	before_create do
	    self.guid = SecureRandom.uuid
	end
end

app/models/device_registry.rb
class DeviceRegistry < ActiveRecord::Base
    belongs_to :device
    belongs_to :device_agent
  # attr_accessible :title, :body
end

app/models/device_type.rb
class DeviceType < ActiveRecord::Base
    attr_accessible :device_type, :version, :manufacturer, :metadata_json, :default_config
    has_many :devices
end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :alt, :format, :lat, :lon, :print_name
end

app/models/locations.rb
class Locations < ActiveRecord::Base
	attr_accessible :alt, :format, :lat, :lon, :print_name
	belongs_to :device
	belongs_to :sensor
	belongs_to :device_agent
end

app/models/sensor.rb
class Sensor < ActiveRecord::Base
  attr_accessible :guid, :uri, :sensor_type_id, :min_value, :max_value, :device_guid, :device_id, :predecessor, :metadata_json, :location, :frequency
  belongs_to :device
  belongs_to :sensor_type
  has_one :location, :dependent => :destroy

	before_create do
	    self.guid = SecureRandom.uuid
	end
end

app/models/sensor_reading.rb
class SensorReading < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/sensor_registry.rb
class SensorRegistry < ActiveRecord::Base
    has_many :sensors
  # attr_accessible :title, :body
end

app/models/sensor_type.rb
class SensorType < ActiveRecord::Base
    attr_accessible :property_type, :metadata_json
    has_many :sensors
end

app/models/sensor_type_registry.rb
class SensorTypeRegistry < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/virtual_device.rb
class VirtualDevice < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/virtual_sensor.rb
class VirtualSensor < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index

  end

  def dashboard

  end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
    respond_to :json, :html

    def index
        @locations = Location.all
        respond_with @locations
    end

    def new
        @location = Location.new
    end
    def create
        @location = Location.new(params[:sensor])
        if @location.save
            flash[:notice] = "Sensor created successfully !"
            redirect_to :action => "index"
        else
            flash[:error] = "Couldn't create the Sensor. Please try again."
            render "new"
        end
    end
    def edit
        @location = Location.find(params[:id])
    end

    def update
        @location = Location.find(params[:id])
        respond_to do |format|
            if @location.update_attributes(params[:sensor])
                flash[:notice] = 'Sensor  was successfully updated.'
                format.html { redirect_to :action => "index" }
                format.json { head :no_content }
            else
              format.html { render action: "edit" }
              format.json { render json: @location.errors, status: :unprocessable_entity }
            end
        end
    end

    def destroy
        @location = Location.find(params[:id])
        @location.delete
        flash[:notice] = "Location deleted successfully !"
        redirect_to :action => "index"
    end

    def show
        redirect_to :action => 'edit'
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/device_types_helper.rb
module DeviceTypesHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/sensor_types_helper.rb
module SensorTypesHelper
end

app/helpers/sensors_helper.rb
module SensorsHelper
end

app/views/locations/_form.html.erb
<%= form_for(@device) do |f| %>
    <% if @device.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@device.errors.count, "error") %> prohibited this device from being registered:</h2>

          <ul>
            <% @device.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <table>
      <tr>
        <td class="field" width="50%"><%= f.label :guid %></td>
        <td class="field"><%= f.text_field :guid %> <span>.device.sv.cmu.edu</span></td>
      </tr>
      <tr>
        <td class="field"><%= f.label :device_type_id %></td>
        <td class="field"><%= f.select("device_type_id", options = @device_types.map { |d| [d.device_type, d.id] }) %></td>
      </tr>
      <tr>
        <td class="field"><%= f.label :device_agent_id %></td>
        <td class="field"><%= f.text_field :device_agent_id %></td>
      </tr>
      <tr>
        <td class="field"><%= f.label :network_address %></td>
        <td class="field"><%= f.text_field :network_address %></td>
      </tr>
      <tr>
        <td style="text-align: right;" colspan="2">
            <div class="actions">
              <%= f.submit %>
            </div>
        </td>
      </tr>
    </table>
<% end %>

app/views/locations/edit.html.erb
<% @page_title = "| Location | Edit" %>

<h1 style="text-align: left;">Edit Location Information</h1>
<%= render 'form' %>
	<h2>Sensors for this device:</h2>
		<table class="field" width="50%">
		<thead>
			<tr>
				<td><u>Child Sensors</u></td>
				<td><u>Sensor Type</u></td>
		<% @locations.each do |location| %>
			<tr>
				<td><%= link_to location.device.guid, edit_device_path(location.device) %></td>
				<td><%=  %></td>
			</tr>
		<% end %>
	</table><br />
<%= link_to 'Back', devices_path %>

app/views/locations/index.html.erb
<% @page_title = "| Device | List" %>

<h1 style="text-align: left;">List of Devices</h1>

    <table class="table">
        <tr>
            <td>Latitude</td>
            <td>Longitude</td>
            <td>Altitude</td>
            <td>physical_location</td>
            <td>device_agent_guid</td>
            <td colspan='2'>Actions</td>
        </tr>
        <% @locations.each do |location| %>
        <tr>
            <td><%= location.lat %></td>
            <td><%= location.lon %></td>
            <td><%= location.alt %></td>
            <td><%=  %></td>
            <td><%= link_to 'Edit', edit_location_path(location) %></td>
            <td><%= link_to 'Delete', location, confirm: 'Are you sure?', method: :delete %></td>
        </tr>
        <% end %>
    </table>

<%= link_to 'New', new_device_path %> | <%= link_to 'Back', root_path %>

app/views/locations/new.html.erb
<% @page_title = "| Location | New" %>

<h1 style="text-align: left;">Location registration</h1>
<%= render 'form' %>
<%= link_to 'Back', locations_path %>