config/routes.rb
CmuSds::Application.routes.draw do
  devise_for :users
  root :to => 'home#index'

  match 'dashboard' => 'home#dashboard', :as => "dashboard"

  resources :sensor_readings, :devices, :device_agents, :sensor_types, :device_types, :locations
  resources :sensors

  match '/get_devices' => 'devices#get_devices'
  match ':controller(/:action(/:id))(.:format)'
end

app/models/conversion.rb
class Conversion < ActiveRecord::Base
  attr_accessible :device_type_id, :quantity, :description, :conversion_type, :a, :b, :chart_min, :chart_max

  belongs_to :device_type

end

app/models/device.rb
class Device < ActiveRecord::Base
    attr_accessible :guid, :uri, :device_type_id, :network_address, :metadata_json, :print_name, :config, :url

    #has_many :device_registries
    has_and_belongs_to_many :device_agents
    belongs_to :device_type
    has_one :location, :dependent => :destroy
    has_many :sensors, :dependent => :destroy

    def as_json(options={})
      {
        :uri => self.uri,
        :sensors => self.sensors
      }
    end

    before_create do
        self.guid = SecureRandom.uuid
    end

end

app/models/device_agent.rb
class DeviceAgent < ActiveRecord::Base
	attr_accessible :guid, :uri, :network_address, :print_name, :metadata_json
	has_and_belongs_to_many :devices
	has_one :location, :dependent => :destroy

  	before_create do
	    self.guid = SecureRandom.uuid
	end
end

app/models/device_registry.rb
class DeviceRegistry < ActiveRecord::Base
    belongs_to :device
    belongs_to :device_agent
  # attr_accessible :title, :body
end

app/models/device_type.rb
class DeviceType < ActiveRecord::Base
    attr_accessible :device_type, :version, :manufacturer, :metadata_json, :default_config
    has_many :devices
end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :alt, :format, :lat, :lon, :print_name
end

app/models/locations.rb
class Locations < ActiveRecord::Base
	attr_accessible :alt, :format, :lat, :lon, :print_name
	belongs_to :device
	belongs_to :sensor
	belongs_to :device_agent
end

app/models/sensor.rb
class Sensor < ActiveRecord::Base
  attr_accessible :guid, :uri, :sensor_type_id, :min_value, :max_value, :device_guid, :device_id, :predecessor, :metadata_json, :location, :frequency
  belongs_to :device
  belongs_to :sensor_type
  has_one :location, :dependent => :destroy

	before_create do
	    self.guid = SecureRandom.uuid
	end
end

app/models/sensor_reading.rb
class SensorReading < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/sensor_registry.rb
class SensorRegistry < ActiveRecord::Base
    has_many :sensors
  # attr_accessible :title, :body
end

app/models/sensor_type.rb
class SensorType < ActiveRecord::Base
    attr_accessible :property_type, :metadata_json
    has_many :sensors
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/virtual_device.rb
class VirtualDevice < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/virtual_sensor.rb
class VirtualSensor < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index

  end

  def dashboard

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/sensors_helper.rb
module SensorsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Carnegie Mellon Silicon Valley - Sensor Data Storage <%= @page_title %></title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= csrf_meta_tags %>
</head>

<body>
  <header id="header" class="navbar navbar-inverse navbar-fixed-top">
    <div class="inner">
      <div class="pull-left">
        <h3 class="title-link">
          <%= link_to "Carnegie Mellon University Silicon Valley", root_path %>
        </h3>
      </div>
      <div class="actions pull-right">
        <h5>
          <%= link_to "Dashboard", dashboard_path %> |
          <%= link_to "Sensors", sensors_path %> |
          <%= link_to "Devices", devices_path %> |
          <%= link_to "Device Agents", device_agents_path %> |
          <%= link_to "Sensor Types", sensor_types_path %> |
          <%= link_to "Device Types", device_types_path %> |
          <% if current_user %>
            <span><%= "Welcome #{current_user.email}" %></span>
            <%= link_to "Log Out", destroy_user_session_path, :method => :delete %>
          <% else %>
            <%= link_to "Log In", new_user_session_path %>
          <% end %>
        </h5>
      </div>
    </div>
  </header>

  <%= yield %>

  <footer class="footer">
    <div class="inner">
      <div class="pull-right">
        Copyright © Carnegie Mellon University - Silicon Valley Campus.
      </div>
    </div>
  </footer>
  <%= javascript_include_tag :application %>
</body>

</html>

app/views/shared/_notice_snippet.html.erb
<% if !flash[:notice].blank? %>
    <div class="notice">
        <%= flash[:notice] %>
    </div>
<% end %>